# Generated by Django 3.2.23 on 2024-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240127_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_time',
            new_name='updated_date',
        ),
    ]
